image: tobiasb/php-cli:7.3
options:
  docker: true
  size: 2x

pipelines:
  default:
    - parallel:
      - step:
          name: Unit/functional tests and static code analysis
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/code_tests.sh
          artifacts:
            - php_error.log
      - step:
          name: Content features
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh content db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
            - "*.png"
            - "*.html"
      - step:
          name: Entities features
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh entities db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
            - "*.png"
            - "*.html"
      - step:
          name: Access features
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh access db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
            - "*.png"
            - "*.html"
      - step:
          name: View mode features
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh view_mode db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
            - "*.png"
            - "*.html"
      - step:
          name: Form features
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh form db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
            - "*.png"
            - "*.html"
      - step:
          name: Simplenews feature
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh simplenews db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
            - "*.png"
            - "*.html"
      - step:
          name: Social media sharing feature
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh social_media_sharing db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
            - "*.png"
            - "*.html"
      - step:
          name: Smoke tests
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh smoke_tests db_dump
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.sql.gz"
            - "*.png"
            - "*.html"
      - step:
          name: Frontend tests
          caches:
            - composer
          script:
            - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh backstopjs db_dump
            - ERROR=0 bash $BITBUCKET_CLONE_DIR/scripts/pipeline/html_validation.sh
          services:
            - docker
            - testing
          artifacts:
            - php_error.log
            - "*.tar.gz"
  branches:
    release/*:
      - parallel:
        - step:
            name: Unit/functional tests and static code analysis
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/code_tests.sh
            artifacts:
              - php_error.log
        - step:
            name: Content features
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh content install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
              - "*.png"
              - "*.html"
        - step:
            name: Entities features
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh entities install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
              - "*.png"
              - "*.html"
        - step:
            name: Access features
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh access install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
              - "*.png"
              - "*.html"
        - step:
            name: View mode features
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh view_mode install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
              - "*.png"
              - "*.html"
        - step:
            name: Form features
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh form install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
              - "*.png"
              - "*.html"
        - step:
            name: Simplenews feature
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh simplenews install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
              - "*.png"
              - "*.html"
        - step:
            name: Social media sharing feature
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh social_media_sharing install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
              - "*.png"
              - "*.html"
        - step:
            name: Smoke tests
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh smoke_tests install
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.sql.gz"
              - "*.png"
              - "*.html"
        - step:
            name: Frontend tests
            caches:
              - composer
            script:
              - bash $BITBUCKET_CLONE_DIR/scripts/pipeline/acceptance_tests.sh backstopjs install
              - ERROR=0 bash $BITBUCKET_CLONE_DIR/scripts/pipeline/html_validation.sh
            services:
              - docker
              - testing
            artifacts:
              - php_error.log
              - "*.tar.gz"

definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless
      memory: 2048
    docker:
      memory: 2048
