version: "2"
services:
  testing:
    container_name: "testing"
    image: "derh4nnes/selenium-chrome-headless"
    working_dir: "/opt/atlassian/pipelines/agent/build/degov-project"
    ports:
      - "4444:4444"
    volumes:
      - "/opt/atlassian/pipelines/agent/build/degov-project/docroot/profiles/contrib/degov/testing/fixtures:/home/headless/"
      - "/opt/atlassian/pipelines/agent/build:/opt/atlassian/pipelines/agent/build"
    networks:
      backend:
        ipv4_address: 172.16.31.3
  app:
    image: "derh4nnes/pipeline-behat:feature_php-7.2"
    container_name: "app"
    ports:
      - "80:80"
    environment:
      BITBUCKET_BRANCH: "$BITBUCKET_BRANCH"
      BITBUCKET_COMMIT: "$BITBUCKET_COMMIT"
    entrypoint: /bin/bash
    command: /opt/atlassian/pipelines/agent/build/scripts/pipeline.sh 7.2
    volumes:
      - "/opt/atlassian/pipelines/agent/build:/opt/atlassian/pipelines/agent/build"
    networks:
      backend:
        ipv4_address: 172.16.31.2
  mysql:
    image: mechtecs/docker_big_mysql
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_DATABASE: testing
    ports:
      - "3306:3306"
    networks:
      backend:
        ipv4_address: 172.16.31.4

networks:
  backend:
    ipam:
      config:
        - subnet: 172.16.31.0/24
          gateway: 172.16.31.1
