dependencies:
  config:
    - field.field.node.normal_page.field_scheduled_publish
  module:
    - scheduled_publish
content:
  field_scheduled_publish:
    type: scheduled_publish
    weight: 11
    region: content
    settings: {  }
    third_party_settings: {  }
