version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - code_tests:
          requires:
            - build
      # - integration_tests:
      #     requires:
      #       - build
jobs:
  build:
    docker:
      - image: tobiasb/php-cli:7.3-debian
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: "Fix CIRCLE_WORKING_DIRECTORY"
          command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
      - run:
          name: "Create project"
          command: |
            bash ./scripts/ci/composer--create.sh
            cp ~/app/project/composer.lock /tmp/composer.lock
      - restore_cache:
          keys:
            - composer-{{ checksum "/tmp/composer.lock" }}
      - run:
          name: "Install project"
          command: bash ./scripts/ci/composer--install.sh
      - run:
          name: "Run post install"
          command: bash ./scripts/ci/composer--postinstall.sh
      - save_cache:
          key: composer-{{ checksum "/tmp/composer.lock" }}
          paths:
            - ~/.composer
            - ~/app/project
      - persist_to_workspace:
          root: project
          paths:
            - .
  code_tests:
    docker:
      - image: tobiasb/php-cli:7.3-debian
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: "Fix CIRCLE_WORKING_DIRECTORY"
          command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
      - attach_workspace:
          at: project
      - run:
          name: Move code
          command: bash ./scripts/pipeline/default_setup_ci.sh
      - run:
          name: Coding standards
          command: bash ./scripts/ci/checks--cs.sh
      - run:
          name: PHPstan
          command: bash ./scripts/ci/checks--phpstan.sh
      - run:
          name: PHPUnit
          command: bash ./scripts/ci/tests--phpunit.sh
      - store_test_results:
          path: test-reports
  integration_tests:
    docker:
      - image: tobiasb/php-cli:7.3-debian
    working_directory: ~/app
    steps:
      - run:
          name: Install docker client
          command: |
            wget https://download.docker.com/linux/static/stable/x86_64/docker-19.03.9.tgz
            tar xzvf docker-19.03.9.tgz
            cp docker/* /usr/bin/

      - checkout
      - run:
          name: "Fix CIRCLE_WORKING_DIRECTORY"
          command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
      - attach_workspace:
          at: project
      - setup_remote_docker:
      - run:
          name: Content features
          command: bash ./scripts/pipeline/acceptance_tests.sh content db_dump
