version: 2

workflows:
  version: 2
  composer_setup:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/php:7.3-node
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt install git-lfs
      - run:
          name: "Fix CIRCLE_WORKING_DIRECTORY"
          command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
      - restore_cache:
          keys:
            - composer-{{ .Branch }}-{{ checksum "composer.json" }}
            - composer-{{ .Branch }}
            - composer
      - run:
          name: Composer setup
          command: bash ./scripts/pipeline/composer_setup.sh
      - save_cache:
          key: composer-{{ .Branch }}-{{ checksum "composer.json" }}
          paths:
            - ~/.composer
