version: 2

workflows:
  version: 2
  composer_setup:
    jobs:
      - build
      - tests:
          requires:
            - build
jobs:
  build:
    docker:
      - image: cimg/php:7.3-node
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && \
            DEBIAN_FRONTEND=noninteractive sudo apt-get install git-lfs && \
            git lfs install
      - run:
          name: "Fix CIRCLE_WORKING_DIRECTORY"
          command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
      - restore_cache:
          keys:
            - composer-{{ .Branch }}-{{ checksum "composer.json" }}
            - composer-{{ .Branch }}
            - composer
      - run:
          name: Composer setup
          command: bash ./scripts/pipeline/composer_setup.sh
      - save_cache:
          key: composer-{{ .Branch }}-{{ checksum "composer.json" }}
          paths:
            - ~/.composer
      - persist_to_workspace:
          root: ~/app
          paths:
            - project/
  tests:
    docker:
      - image: cimg/php:7.3-node
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: "Fix CIRCLE_WORKING_DIRECTORY"
          command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/app/project
      - run:
          name: Unit/functional tests and static code analysis
          command: bash ./scripts/pipeline/shared_scripts/code_tests.sh
