version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      # - code_tests:
      #     requires:
      #       - build
      - integration_tests:
          requires:
            - build
jobs:
  build:
    docker:
      - image: tobiasb/php-cli:7.3-debian
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: "Fix CIRCLE_WORKING_DIRECTORY"
          command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
      - restore_cache:
          keys:
            - composer-{{ .Branch }}-{{ checksum "source/pipeline/.env" }}
      - run:
          name: Composer setup
          command: bash ./scripts/pipeline/composer_setup.sh
      - save_cache:
          key: composer-{{ .Branch }}-{{ checksum "source/pipeline/.env" }}
          paths:
            - ~/.composer
      - persist_to_workspace:
          root: project
          paths:
            - .
  code_tests:
    docker:
      - image: tobiasb/php-cli:7.3-debian
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: "Fix CIRCLE_WORKING_DIRECTORY"
          command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
      - attach_workspace:
          at: project
      - run:
          name: Unit/functional tests and static code analysis
          command: bash ./scripts/pipeline/shared_scripts/code_tests.sh
  integration_tests:
    docker:
      - image: tobiasb/php-cli:7.3-debian
    working_directory: ~/app
    steps:
      - run:
          name: Install docker client
          command: |
            apt update
            DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -yq \
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg-agent \
              software-properties-common
            curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
            add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/debian \
              $(lsb_release -cs) \
              stable"
            apt update
            DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -yq \
              docker-ce-cli \
              containerd.io
      - checkout
      - run:
          name: "Fix CIRCLE_WORKING_DIRECTORY"
          command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
      - attach_workspace:
          at: project
      - setup_remote_docker:
      - run:
          name: Content features
          command: bash ./scripts/pipeline/acceptance_tests.sh content db_dump
