cf5d9a31-e053-413a-8666-a2c3fedbc4a0:
  settings:
    form_mode: media_browser
    media_type: image
    upload_location: 'public://images/[date:custom:Y]-[date:custom:m]'
    dropzone_description: 'Drop files here to upload them'
    max_filesize: 32M
    extensions: 'jpg jpeg gif png'
    submit_text: 'Select entities'
  uuid: cf5d9a31-e053-413a-8666-a2c3fedbc4a0
  weight: -9
  label: 'Bilder hochladen'
  id: dropzonejs_media_entity_inline_entity_form
