content:
  thumbnail:
    type: responsive_image
    settings:
      responsive_image_style: teaser_squared
      image_link: content
  field_video_preview:
    type: entity_reference_entity_view
    settings:
      view_mode: teaser_squared_1_1
      link: true
