name: 'deGov - Rich Text Format - Settings'
description: 'Activates Spamspan obfuscation of the E-Mail addresses for the Richt Text Format'
type: module
package: deGov
core: 8.x
dependencies:
  - drupal:filter
  - drupal:editor
  - drupal:ckeditor
  - drupal:linkit
  - drupal:node
  - drupal:media
  - entity_embed:entity_embed
  - spamspan:spamspan
  - embed:embed
  - editor_advanced_link:editor_advanced_link
